 name: Automated Triage

  on:
   issues:
    types:
    - opened
    - labeled
  pull_request:
   types:
     - opened
     - labeled
    
 jobs:
  triage:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout Repository
     - uses: actions/setup-python@v2

     - name: Sep up Python
       uses: actions/setup-python@v2
       with:
        
        python-version: 3.8 # Specify the python version you need

     - name: Install dependecies
       run: |
          python -m pip install --upgrade pip
          pip install -r requiment.txt # Replace with your reuirment file

  -name: Execute Python Scipt
    run: |
        # Replace 'your_script.py with the actual name of your Python script
    python my.py
    
